const menuList = [
    {
        key:'submit',
        title:"防抖 || 节流",
        icon:"apple",
        path:"/"
    },
    {
        key:"slot",
        title:"插槽",
        icon:"qq",
        path:"/slot"
    },
    {
        key:"formValidate",
        title:"表单验证",
        icon:"android",
        path:"/formValidate"
    },
    {
        key:"graphics",
        title:"特殊图形",
        icon:"ie",
        path:"/graphics"
    },
    {
        key:"loading",
        title:"加载动画",
        icon:"github",
        path:"/loading"
    },
    {
        key:"bigger",
        title:"图片放大器",
        icon:"dingding",
        path:"/bigger"
    },
    {
        key:"chart",
        title:"Echart图表",
        icon:"wechat",
        path:"/chart"
    },
    {
        key:"trajectory",
        title:"弹道",
        icon:"taobao-circle",
        path:"/trajectory"
    },
    {
        key:'draggable',
        title:'拖拽组件',
        icon:"taobao-circle",
        path:'/draggable'
    }
]
export default menuList
